.\" man page for libexpbuf
.\" Contact dev@hyper-active.com.au to correct errors or omissions. 
.TH expbuf_t 3 "23 October 2008" "1.0" "Library for Expanding Buffer."
.SH NAME
expbuf_t \- expanding buffer structure.
.SH SYNOPSIS
.B #include <expbuf.h>
.sp
.B typedef struct
.br
.B {
.br
.B 	char *data;
.br
.B 	unsigned int length;
.br
.B 	unsigned int max;
.br
.B } expbuf_t;
.sp
.SH DESCRIPTION
.B expbuf_t
is a simple structure that is managed by the libexpbuf library.  It contains a dynamically increased buffer.
.br
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_add (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_shrink (3)
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
on behalf of Hyper-Active Systems, Australia.
.br
http://www.hyper-active.com.au/libexpbuf/
.fi
.SH HISTORY
Oct 23, 2008 \- Initial v1.0 release made public.
