.\" man page for libexpbuf
.\" Contact dev@hyper-active.com.au to correct errors or omissions. 
.TH expbuf_add 3 "23 October 2008" "1.0" "libexpbuf - Library for a simple Expanding Buffer."
.SH NAME
expbuf_add \- Add data to the buffer.
.SH SYNOPSIS
.B #include <expbuf.h>
.sp
.B void expbuf_add(expbuf_t *buf, void *data, unsigned int len);
.br
.SH EXAMPLES
#include <expbuf.h>
.sp
int main(void) {
.br
	expbuf_t buffer;
.br
	char data[1024]];
.br
	int len, avail;
.sp
	expbuf_init(&buffer, 0);
.br
	len = read_data(data, 1024);
.br
	while (len >= 0) {
.br
		expbuf_add(&buffer, data, len);
.br
		processed = process_data(buffer.data, buffer.length);
.br
		expbuf_purge(&buffer, processed);
.br
		len = read_data(data);
.br
	}
.br
	expbuf_free(&buffer);
.br
	return(0);
.br
}
.SH DESCRIPTION
.B expbuf_add()
is used to add data to the buffer, expanding it if needed.  If there is already data in the buffer, the new data will be added to the end of it.  If there is not enough memory allocated, it will resize the amount of memory as needed.
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_shrink (3),
.BR expbuf_t (3)
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
on behalf of Hyper-Active Systems, Australia.
.br
http://www.hyper-active.com.au/libexpbuf/
.fi
.SH HISTORY
Oct 23, 2008 \- Initial v1.0 release made public.
