.\" man page for libexpbufpool
.\" Raise ticket to https://github.com/clintwebb/libexpbuf to correct errors or omissions.
.TH expbuf_t 3 "23 October 2008" "1.0" "Library for managing a pool of Expanding Buffers."
.SH NAME
expbuf_pool_t \- expanding buffer pool structure.
.SH DESCRIPTION
.B expbuf_pool_t
is a simple library used to manage a pool of libexpbuf expanding buffers.  It does not do anything fancy, just something often used in relation to using buffers.
.br
.SH SEE ALSO
.BR libexpbuf (3)
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.br
https://github.com/clintwebb/libexpbuf
.fi
.SH HISTORY
Oct 23, 2008 \- Initial v1.0 release made public.
