.\" man page for libexpbuf
.\" Contact dev@rhokz.com to correct errors or omissions. 
.TH expbuf_set 3 "1 March 2011" "1.04" "libexpbuf - Library for a simple Expanding Buffer."
.SH NAME
expbuf_set \- Add data to the buffer, overwriting what is already there.
.SH SYNOPSIS
#include <expbuf.h>
.sp
void 
.B expbuf_set
(expbuf_t *buf, void *data, unsigned int len);
.br
.SH EXAMPLES
.nf
#include <expbuf.h>

int main(void) {
	expbuf_t buffer;
	char data[1024]];
	int len, avail, processed;
	expbuf_init(&buffer, 0);
	len = read_data(data, 1024);
	while (len >= 0) {
		expbuf_set(&buffer, data, len);
		processed = process_data(buffer.data, buffer.length);
		len = read_data(data, 1024);
	}
	expbuf_free(&buffer);
	return(0);
}
.fi
.SH DESCRIPTION
.B expbuf_set()
is used to add data to the buffer, expanding it if needed.  If there is already data in the buffer, the new data will be 
written over top of it.  If there is not enough memory allocated, it will resize the amount of memory as needed.  It will 
not reduce the amount of memory allocated.
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_add (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_shrink (3),
.BR expbuf_string (3),
.BR expbuf_t (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.br
https://www.github.com/clintwebb/libexpbuf/
.fi
