.\" man page for libexpbuf
.\" Contact dev@rhokz.com to correct errors or omissions. 
.TH expbuf_clear 3 "1 March 2011" "1.04" "libexpbuf - Library for a simple Expanding Buffer."
.SH NAME
expbuf_clear \- clear out, or empty, the data in the buffer.
.SH SYNOPSIS
#include <expbuf.h>
.sp
void 
.B expbuf_clear
(expbuf_t *buf);
.br
.SH DESCRIPTION
.B expbuf_clear()
is used to clear all the data in the buffer. It does not free any memory, or adjust anything except for the
.I length
field, which is set to zero.   To de-allocate memory, see
.BR expbuf_free (3),
or
.BR expbuf_shrink (3),
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_add (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_set (3),
.BR expbuf_shrink (3),
.BR expbuf_string (3),
.BR expbuf_t (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.br
https://www.github.com/clintwebb/libexpbuf
.fi
