.\" man page for libexpbuf
.\" Contact dev@rhokz.com to correct errors or omissions. 
.TH expbuf_setbuf 3 "1 March 2011" "1.04" "libexpbuf - Library for a simple Expanding Buffer."
.SH NAME
expbuf_setbuf \- Set the contents of one buffer into to the buffer, overwriting it.
.SH SYNOPSIS
#include <expbuf.h>
.sp
void 
.B expbuf_setbuf
(expbuf_t *target, expbuf_t *src);
.br
.SH DESCRIPTION
.B expbuf_setbuf()
is used to set data from one buffer to another buffer, overwriting the 'target' buffer, and expanding it if needed.  If 
there is already data in the buffer, the new data will be added to the end of it.  If there is not enough memory allocated, 
it will resize the amount of memory as needed.
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_add (3),
.BR expbuf_addbuf (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_set (3),
.BR expbuf_shrink (3),
.BR expbuf_string (3),
.BR expbuf_t (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.br
https://www.github.com/clintwebb/libexpbuf
.fi
