.\" man page for libexpbuf
.\" Contact dev@rhokz.com to correct errors or omissions.
.TH expbuf_inc 3 "6 December 2022" "1.04" "libexpbuf - Library for a simple Expanding Buffer."
.SH NAME
expbuf_inc \- Increase the size of the content in the buffer.  This is used primarily only when data has been directly added to the buffer.
.SH SYNOPSIS
.B #include <expbuf.h>
.sp
unsigned int
.B expbuf_inc
(expbuf_t *buf, void *data, unsigned int len);
.br
.SH EXAMPLES
.nf
#include <expbuf.h>

int main(void) {
	expbuf_t buffer;
	int len, avail;
	expbuf_init(&buffer, 1024);
	len = read_data(BUF_OFFSET(&buffer), BUF_AVAIL(&buffer));
	while (len >= 0) {
		expbuf_inc(&buffer, len);
		processed = process_data(buffer.data, buffer.length);
		expbuf_purge(&buffer, processed);
		len = read_data(BUF_OFFSET(&buffer), BUF_AVAIL(&buffer));
	}
	expbuf_free(&buffer);
	return(0);
}
.fi
.SH DESCRIPTION
.B expbuf_inc()
is used to indicate that data was added to the buffer contents.  This is normally used for fixed length buffers, but can certainly
be used in many other situations.
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_addbuf (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_set (3),
.BR expbuf_setbuf (3),
.BR expbuf_shrink (3),
.BR expbuf_string (3),
.BR expbuf_t (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.br
http://www.github.com/clintwebb/libexpbuf
.fi
