.\" man page for libexpbuf
.\" Contact dev@hyper-active.com.au to correct errors or omissions. 
.TH expbuf_t 3 "1 March 2011" "1.04" "Library for Expanding Buffer."
.SH NAME
expbuf_t \- expanding buffer structure.
.SH SYNOPSIS
#include <expbuf.h>
.sp
typedef struct
.br
{
.br
 	char *data;
.br
	unsigned int length;
.br
	unsigned int max;
.br
} 
.B expbuf_t
;
.sp
.SH DESCRIPTION
.B expbuf_t
is a simple structure that is managed by the libexpbuf library.  It contains a dynamically increased buffer.
.br
.SH SEE ALSO
.BR libexpbuf (3),
.BR expbuf_add (3),
.BR expbuf_clear (3),
.BR expbuf_free (3),
.BR expbuf_init (3),
.BR expbuf_purge (3),
.BR expbuf_set (3),
.BR expbuf_shrink (3),
.BR expbuf_string (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
on behalf of Hyper-Active Systems, Australia.
.br
http://www.github.com/hyper/libexpbuf/
.fi
